export const metadata = {
  title: "Terms of Service — KnowWhy",
  description: "Terms governing your use of the KnowWhy platform.",
}

export default function TermsPage() {
  return (
    <article className="prose prose-zinc dark:prose-invert max-w-none">
      <h1>Terms of Service</h1>
      <p className="lead text-zinc-500">Last updated: March 13, 2026</p>

      <p>
        These Terms of Service (&ldquo;Terms&rdquo;) govern your access to and use of KnowWhy and its associated
        APIs, webhooks, and integrations (collectively, the &ldquo;Service&rdquo;). By creating an account or using
        the Service you agree to be bound by these Terms.
      </p>

      <hr />

      <h2>1. Definitions</h2>
      <ul>
        <li><strong>&ldquo;KnowWhy&rdquo;</strong> — the platform and the company operating it.</li>
        <li><strong>&ldquo;Customer&rdquo;</strong> — the organisation or individual that creates an account.</li>
        <li><strong>&ldquo;User&rdquo;</strong> — any individual who uses the Service under a Customer account.</li>
        <li><strong>&ldquo;Content&rdquo;</strong> — decisions, meeting notes, transcripts, and any other data uploaded to
          or generated by the Service.</li>
      </ul>

      <h2>2. Account Registration</h2>
      <p>
        You must provide accurate information when creating an account. You are responsible for
        maintaining the security of your credentials and for all activity under your account.
        You must notify us immediately at{" "}
        {/* TODO: legal review — add security contact email */}
        <a href="mailto:security@knowwhy.app">security@knowwhy.app</a> of any unauthorised access.
      </p>

      <h2>3. Ownership of Content</h2>
      <p>
        <strong>You own your Content.</strong> KnowWhy does not claim any intellectual property rights
        over the decisions, meeting transcripts, or other data you submit. We process your Content
        solely to deliver the Service described in these Terms.
      </p>
      <p>
        You grant KnowWhy a limited, non-exclusive, royalty-free licence to store, process, and
        display your Content as necessary to provide and improve the Service.
      </p>

      <h2>4. Data Handling and Privacy</h2>
      <p>
        Our collection and use of personal data is described in the{" "}
        <a href="/privacy">Privacy Policy</a>. Where KnowWhy processes personal data on your behalf as
        a data processor, the{" "}
        <a href="/dpa">Data Processing Agreement (DPA)</a> applies and is incorporated into these Terms
        by reference.
      </p>

      <h2>5. Service Level Agreement (SLA)</h2>
      <table>
        <thead>
          <tr>
            <th>Deployment</th>
            <th>Uptime target</th>
            <th>Status page</th>
          </tr>
        </thead>
        <tbody>
          <tr>
            <td>SaaS (managed)</td>
            <td>99.5% monthly uptime</td>
            <td><a href="/status">status.knowwhy.app</a></td>
          </tr>
          <tr>
            <td>Self-hosted / VPC</td>
            <td>Customer-managed; no SLA from KnowWhy</td>
            <td>N/A</td>
          </tr>
        </tbody>
      </table>
      <p>
        {/* TODO: legal review — define credit structure for SLA breaches */}
        Planned maintenance is excluded from uptime calculations. In the event of unplanned downtime
        exceeding the SLA, Customers on paid plans may request a service credit as defined in their
        order form.
      </p>

      <h2>6. Acceptable Use</h2>
      <p>You agree not to:</p>
      <ul>
        <li>Use the Service to transmit unlawful, infringing, or harmful content.</li>
        <li>Reverse-engineer, decompile, or attempt to extract source code.</li>
        <li>Circumvent rate limits or authentication mechanisms.</li>
        <li>Use the Service to train or fine-tune AI models without written consent.</li>
        <li>Resell or sublicense access to the Service without a written reseller agreement.</li>
      </ul>

      <h2>7. Third-Party Integrations</h2>
      <p>
        The Service integrates with Slack, GitLab, and Google Calendar. These integrations are optional,
        governed by the respective third-party terms, and can be disconnected at any time via{" "}
        <a href="/settings">Settings → Integrations</a>. KnowWhy requests only the minimum OAuth
        scopes necessary for the selected features.
      </p>

      <h2>8. AI-Generated Content</h2>
      <p>
        The Service uses AI models (Groq LLM or self-hosted Ollama) to extract and summarise decisions.
        AI outputs may contain errors. You are responsible for reviewing and validating any
        AI-generated decision records before acting on them.
      </p>

      <h2>9. Payment and Billing</h2>
      <p>
        {/* TODO: legal review — add pricing, billing cycle, refund policy */}
        Billing terms are specified in the applicable order form or subscription plan. All fees are
        non-refundable except where required by applicable law.
      </p>

      <h2>10. Termination</h2>
      <p>
        Either party may terminate at any time. Upon termination: (a) your access is revoked; (b)
        your Content is deleted within 30 days unless you have initiated a data export beforehand.
        You may export your data at any time via{" "}
        <a href="/settings">Settings → Security → Export Data</a>.
      </p>

      <h2>11. Warranty Disclaimer</h2>
      <p>
        THE SERVICE IS PROVIDED &ldquo;AS IS&rdquo; WITHOUT WARRANTIES OF ANY KIND, EXPRESS OR IMPLIED, INCLUDING
        WARRANTIES OF MERCHANTABILITY, FITNESS FOR A PARTICULAR PURPOSE, OR NON-INFRINGEMENT.
      </p>

      <h2>12. Limitation of Liability</h2>
      <p>
        {/* TODO: legal review — cap liability, jurisdiction-specific carve-outs */}
        TO THE MAXIMUM EXTENT PERMITTED BY LAW, KNOWWHY&apos;S AGGREGATE LIABILITY SHALL NOT EXCEED THE
        AMOUNTS PAID BY YOU IN THE 12 MONTHS PRECEDING THE CLAIM.
      </p>

      <h2>13. Governing Law and Dispute Resolution</h2>
      <p>
        {/* TODO: legal review — choose governing jurisdiction */}
        These Terms are governed by the laws of [JURISDICTION]. Disputes shall be resolved
        by binding arbitration under [ARBITRATION RULES], except that either party may seek
        injunctive relief in a court of competent jurisdiction.
      </p>

      <h2>14. Changes to Terms</h2>
      <p>
        We may update these Terms. Material changes will be communicated by email or in-app notice
        at least 30 days in advance. Continued use constitutes acceptance.
      </p>

      <h2>15. Contact</h2>
      <p>
        Legal enquiries: <a href="mailto:legal@knowwhy.app">legal@knowwhy.app</a>
      </p>
    </article>
  )
}
